<?php 
/**
 * ZF2 Buch Kapitel 14
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 14.8 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 14.8</h1>
<h3>Passwörter verschlüsseln mit <code>Zend\Crypt\Password\Bcrypt</code></h3>
<pre>
&lt;?php
use Zend\Crypt\Password\Bcrypt;
use Zend\Debug\Debug;

$password = 'luigi';
$salt     = 'dasSalzMussMindestens16ZeichenLangSein';
$bcrypt   = new Bcrypt();
$bcrypt->setSalt($salt);

for ($cost = 4; $cost <= 14; $cost++) {
    $bcrypt->setCost($cost);
    $hash = $bcrypt->create($password);
    Debug::dump($cost);
    Debug::dump($hash);
    Debug::dump($bcrypt->verify($password, $hash));
}
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Crypt\Password\Bcrypt;
use Zend\Debug\Debug;

$password = 'luigi';
$salt     = 'dasSalzMussMindestens16ZeichenLangSein';
$bcrypt   = new Bcrypt();
$bcrypt->setSalt($salt);

for ($cost = 4; $cost <= 14; $cost++) {
    $bcrypt->setCost($cost);
    $hash = $bcrypt->create($password);
    Debug::dump($cost);
    Debug::dump($hash);
    Debug::dump($bcrypt->verify($password, $hash));
}
?>
</div>
</div>
