<?php 
/**
 * ZF2 Buch Kapitel 14
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 14.3 view script
 * 
 * @package    Application
 */
use Zend\Http\PhpEnvironment\Request;
use Zend\Soap\AutoDiscover;
use Zend\Soap\Server;

ob_clean();

$url     = $this->serverUrl() . '/listing/listing1403';
$request = $this->getHelperPluginManager()->getServiceLocator()->get('request');

if ($request->getQuery('wdsl') == 'show') {
    $autodiscover = new AutoDiscover();
    $autodiscover->setUri($url);
    $autodiscover->setClass('Pizza\Soap\Server');
    echo $autodiscover->toXml();
} else {
    $server = new Server();
    $server->setUri($url);
    $server->setClass('Pizza\Soap\Server');
    echo $server->handle();
}

exit;
