<?php 
/**
 * ZF2 Buch Kapitel 14
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 14.2 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 14.2</h1>
<h3>Service-Klasse für <code>Zend\Soap\Server</code></h3>
<pre>
&lt;?php
namespace Pizza\Soap;

class Server
{
    protected $pizzaList = array(
        '1' => 'Salami',
        '2' => 'Hawaii',
        '3' => 'Melone',
    );
    
    /**
     * @param integer $id
     * @param string $name
     * @return string
     */
    public function deliverPizza($id, $name)
    {
        $text = 'Lieber ' . $name . ', deine Pizza ';
        $text.= isset($this->pizzaList[$id]) ? $this->pizzaList[$id] : 'XXX';
        $text.= ' wurde gebacken und ausgeliefert!';
        
        return $text;
    }
    
    /**
     * @return array
     */
    public function showPizzas()
    {
        return $this->pizzaList;
    }
}
</pre>
</div>
</div>
