<?php 
/**
 * ZF2 Buch Kapitel 14
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 14.10 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 14.10</h1>
<h3>Einsatz vom <code>ClassMethods</code> Hydrator mit Klasse <code>PizzaEntity</code></h3>
<pre>
&lt;?php
use Pizza\Entity\PizzaEntity;
use Zend\Stdlib\Hydrator\ClassMethods;

$data = array(
    'id'    => '123',
    'name'  => 'Pizza Salami',
    'price' => 6.95,
);

$entity   = new PizzaEntity();
$hydrator = new ClassMethods();
$hydrator->hydrate($data, $entity);

Debug::dump($entity);

$entity->setId('987');
$entity->setName('Pizza Melone');
$entity->setPrice(7.95);

Debug::dump($hydrator->extract($entity));
</pre>
<h3>Ausgabe</h3>
<?php
use Pizza\Entity\PizzaEntity;
use Zend\Debug\Debug;
use Zend\Stdlib\Hydrator\ClassMethods;

$data = array(
    'id'    => '123',
    'name'  => 'Pizza Salami',
    'price' => 6.95,
);

$entity   = new PizzaEntity();
$hydrator = new ClassMethods();
$hydrator->hydrate($data, $entity);

Debug::dump($entity);

$entity->setId('987');
$entity->setName('Pizza Melone');
$entity->setPrice(7.95);

Debug::dump($hydrator->extract($entity));
?>
</div>
</div>
