<?php 
/**
 * ZF2 Buch Kapitel 14
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 14</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing1401">Listing 14.1</a></td>
<td>HTTP-Anfragen senden und verarbeiten mit <code>Zend\Http\Client</code></td>
</tr>
<tr>
<td><a href="/listing/listing1402">Listing 14.2</a></td>
<td>Service-Klasse für <code>Zend\Soap\Server</code></td>
</tr>
<tr>
<td><a href="/listing/listing1403">Listing 14.3</a></td>
<td><code>Zend\Soap\Server</code> Verarbeitung</td>
</tr>
<tr>
<td><a href="/listing/listing1404">Listing 14.4</a></td>
<td><code>Zend\Soap\Client</code> ruft <code>Zend\Soap\Server</code> auf</td>
</tr>
<tr>
<td><a href="/listing/listing1405">Listing 14.5</a></td>
<td>Service-Klasse für <code>Zend\XmlRpc\Server</code></td>
</tr>
<tr>
<td><a href="/listing/listing1406">Listing 14.6</a></td>
<td><code>Zend\XmlRpc\Server</code> Verarbeitung</td>
</tr>
<tr>
<td><a href="/listing/listing1407">Listing 14.7</a></td>
<td><code>Zend\XmlRpc\Client</code> ruft <code>Zend\XmlRpc\Server</code> auf</td>
</tr>
<tr>
<td><a href="/listing/listing1408">Listing 14.8</a></td>
<td>Passwörter verschlüsseln mit <code>Zend\Crypt\Password\Bcrypt</code></td>
</tr>
<tr>
<td><a href="/listing/listing1409">Listing 14.9</a></td>
<td><code>PizzaEntity</code> Klasse</td>
</tr>
<tr>
<td><a href="/listing/listing1410">Listing 14.10</a></td>
<td>Einsatz vom <code>ClassMethods</code> Hydrator mit Klasse <code>PizzaEntity</code></td>
</tr>
</tbody>
</table>
